name: Discord bot CD

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create dotenv file
        run: |
          touch .env.production
          echo "${{ secrets.PROD_ENV }}" >> .env.production

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: badroom
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./packages/discord
          push: true
          tags: badroom/anything:new-book-bot

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted]
    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script_stop: true
          script: |
            sudo docker login -u badroom -p ${{ secrets.DOCKER_TOKEN }}
            sudo docker stop new-book-bot
            sudo docker rm new-book-bot
            sudo docker rmi badroom/anything:new-book-bot
            sudo docker pull badroom/anything:new-book-bot
            sudo docker run -d --name new-book-bot badroom/anything:new-book-bot
